In [1]:
! pip install numpy

### NumPy Basics

1.1 Why NumPy?

- Python lists are slow for large datasets.
- NumPy arrays are optimized, use vectorized operations.
- Essential for ML data preprocessing and computation.



In [2]:
import numpy as np
arr = [1,2,3,4,5]

np_arr = np.array(arr)
print(np_arr)
print(type(np_arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
np.ndim([[
    [2,3],[2,3]
    ]])

3

In [ ]:
# 2D array
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

# 3D array
_matrix = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("==============")
_matrix

[[1 2 3]
 [4 5 6]]


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

##### Array Operations

In [10]:
# 2D array
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print("shape",matrix.shape)
print("dimention",matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
shape (2, 3)
dimention 2
int64


#### Special Arrays

In [11]:
np.zeros((3,3)) # 3x3 zero matrix
np.ones((2,4)) # 2x4 ones matrix
np.arange(0,10,2) # 0 ǂথে=কে 10, step 2
np.linspace(0,1,5) # 0 ǂথে=কে 1, 5 equal parts
np.random.rand(3,3) # random 0-1
np.random.randint(0,10,(2,3)) # random integers



array([[4, 9, 4],
       [9, 8, 6]])

In [12]:
np.zeros((3,3)) # 3x3 zero matrix


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:

np.ones((2,4)) # 2x4 ones matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.zeros((3,3)) # 3x3 zero matrix
np.ones((2,4)).dtype # 2x4 ones matrix


dtype('float64')

##### Difference between  arange  and  linspace .
- arange(start, stop, step)  → uses `step size`
- linspace(start, stop, num)  → divides interval into  `num  equal parts`


In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr1d = np.array([10,20,30])
print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


In [ ]:
np.random.rand(3,3) # random 0-1
np.random.randint(0,10,(2,3)) # random integers & 2D matrix


array([[5, 2, 8],
       [7, 6, 8]])

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a / 2)
print(a * b)

[5 7 9]
[0.5 1.  1.5]
[ 4 10 18]


In [29]:
a = np.arange(6)
print(a.reshape(2,3)) # 2x3 matrix
print(a.flatten()) # 1D array

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [33]:
a = np.array([10,20,30,40,50])
a[0]
a[:-1]
a[a>20]

array([30, 40, 50])

#### Matrix Operations

👉 Transpose :

- row → column

- column → row

In [41]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A @ B) # matrix multiplication
print(np.dot(A,B)) # same
print(np.transpose(A)) # transpose
print(np.linalg.inv(A)) # inverse

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


`np.transpose(A) swaps rows and columns of a matrix. It is used extensively in linear algebra and machine learning for matrix multiplication and data transformation.`

In [83]:
print(np.transpose(A)) # transpose
A


[[1 2]
 [2 3]]


array([[1, 2],
       [2, 3]])

#### Aggregation / Statistics

In [44]:
a = np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.max(a))
print(np.min(a))

15
3.0
3.0
1.4142135623730951
2.0
5
1


#### ML-focused
##### Normalize a dataset (Z-score)

In [59]:
arr = np.array([1,2,3,4,5])
normalized = (arr - np.mean(arr)) / np.std(arr)
print(normalized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]




##### Standardize features



In [74]:
X = np.random.rand(5,3)
X_std = (X - X.mean(axis=0)) / X.std(axis=0)
print(X_std)

[[-0.41226424  1.75729879  1.71115441]
 [-0.8798711   0.39559029 -0.53871511]
 [-0.74166267 -0.92545059  0.51106699]
 [ 0.16906815 -0.88357835 -0.61432136]
 [ 1.86472987 -0.34386014 -1.06918493]]


##### Linear regression formula

    β=(X.T X)−1 X.T y 

    

In [75]:
# y = Xb
X = np.random.rand(5,3)
y = np.random.rand(5,1)
b = np.linalg.inv(X.T @ X) @ X.T @ y
print(b)

[[ 0.52486655]
 [-0.29689987]
 [ 0.7206307 ]]


In [77]:
X.T @ X

array([[2.3207194 , 1.86954421, 0.95165533],
       [1.86954421, 2.07679005, 0.76032912],
       [0.95165533, 0.76032912, 0.55781442]])

##### Vectorized sigmoid

In [78]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

z = np.array([-1,0,1])
print(sigmoid(z))

[0.26894142 0.5        0.73105858]


#### Eigenvalues & Eigenvectors.

In [79]:
A = np.array([[1,2],[2,3]])
vals, vecs = np.linalg.eig(A)
print(vals)
print(vecs)

[-0.23606798  4.23606798]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [70]:
arr = np.random.randint(0,10,(3,4)) ## 3x4 matrix
np.random.shuffle(arr)
print(arr)

[[6 5 7 8]
 [8 3 8 2]
 [4 0 2 9]]


In [84]:
# randomly rearranges elements of an array in-place. 
# For 2D arrays, it shuffles rows only and returns None.

np.random.shuffle(arr)


#### Logical Operations

In [45]:
a = np.array([1,2,3,4,5])
print(np.where(a>3, 'Yes', 'No')) # ['No' 'No' 'No' 'Yes' 'Yes']

['No' 'No' 'No' 'Yes' 'Yes']


In [ ]:
np.random.seed(42) # reproducible & lock the elements
X = np.random.rand(5,3) # 5 rows, 3 features
print(X)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


#### Create a 3x3 identity matrix.

In [54]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [55]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr, axis=0)) # column sum [5 7 9]
print(np.sum(arr, axis=1)) # row sum [6 15]

[5 7 9]
[ 6 15]


In [56]:
arr = np.array([1,2,3,4,5,6])
arr[arr%2==0] # [2 4 6]

array([2, 4, 6])

In [58]:
arr = np.array([-1,2,-3,4])
arr[arr<0] = 0 # [0 2 0 4]
arr

array([0, 2, 0, 4])